Update check_var_2.yml

diff --git a/.github/workflows/check_var_2.yml b/.github/workflows/check_var_2.yml
--- a/.github/workflows/check_var_2.yml
+++ b/.github/workflows/check_var_2.yml
@@ -14,3 +14,7 @@ jobs:
          then JOB_FAILED=true
          fi
          echo "JOB_FAILED is ${JOB_FAILED}"
+         if (JOB_FAILED)
+         echo "JOB_FAILED is ${JOB_FAILED}"
+         exit 1
+         fi
